var alunos = [
    "Acquiles Cardim Prates Guedes",
    "Alana Karoline Souza Costa",
    "André Luis de Melo e Silva",
    "Arthur da Rosa Borges Silvestre",
    "Arthur Francisco Das Chagas",
    "Arthur Pereira Sales",
    "Caio Henrique Patricio",
    "Cauã Mendonça Cabral",
    "Claudio Felipe Morais Da Silva",
    "Daniel Henrique Rocha dos Santos",
    "Davi Luca Freitas de Oliveira",
    "Emerson Aurélio Nunes das Neves",
    "Gabriela Pires Silva do Nascimento",
    "Guilherme Augusto Ferreira Raposo",
    "Guilherme Nemésio Barreto",
    "Guilherme Sales do Nascimento Oliveira",
    "Inácio Azevedo Dantas Neto",
    "Jean Guilherme Brito Cardoso",
    "João Carlos De Almeida Santos Barbosa",
    "João Fillipe Freitas Mourão",
    "José Arthur Moura Tavares",
    "Lucas Cassiano César",
    "Lucas Emmanoel Morais de Albuquerque",
    "Lucas Gabriel Lima do Nascimento",
    "Matheus Antonio Santos Lins",
    "Matheus Henrique Fernandes De Vasconcelos",
    "Matheus Phelipe Albuquerque Nascimento",
    "Matheus Vascurado ",
    "Miguel Vitor Bezerra da Silva",
    "Millarys Santos de Souza",
    "Pedro Henrique Ramos de Lucena",
    "Pedro Isaac Bezerra Sales Curvelo",
    "Pedro Lucas Silva Pontes",
    "Priscilla Barreto Silveira de Souza",
    "Sabrina Ferreira Lins Couto",
    "Sophia Maria Lima da Costa",
    "Suelen Regina De Freitas Alves",
    "Theo Vieira Marcelino",
    "Tiago Abraão Oliveira Luz",
    "Vinícius Gabriel Soares da Silva",
    "Vinícius Silva Cabral",
    "Vitor Barbosa Marins",
    ]
    alunos [43] 
    console.log(alunos)
    console.log(alunos.length)
    console.log(`os alunos esta na posição ${alunos.indexOf ("Matheus Antonio Santos Lins")}`)